version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  redis_data: